<?php
add_action('tdc_init', function(){
    new td_custom_features();
}, 11);

class td_custom_features {
    var $plugin_url = '';
    var $plugin_path = '';
    function __construct()
    {
        $this->plugin_url = plugins_url('', __FILE__); // path used for elements like images, css, etc which are available on end user
        $this->plugin_path = dirname(__FILE__); // used for internal (server side) files


        add_action( 'tdc_loaded' , function() {

            // Add shortcode
            //add the api code inside this function
            td_api_block::add('td_block_chat',
                array(
                    "map_in_visual_composer" => true,
                    "map_in_td_composer" => true,
                    "name" => 'TD Chat',
                    "base" => 'td_block_chat',
                    "class" => 'td_block_chat',
                    "controls" => "full",
                    "category" => 'Blocks',
                    "tdc_category" => 'External',
                    //'icon' => 'icon-pagebuilder-td_block_77',
                    'file' => $this->plugin_path . '/blocks/td_block_chat.php',
                    'params' => array_merge(
                        array(

                            array(
                                'param_name' => 'el_class',
                                'type' => 'textfield',
                                'value' => '',
                                'heading' => 'Extra class',
                                'description' => 'Style particular content element differently - add a class name and refer to it in custom CSS',
                                'class' => 'tdc-textfield-extrabig',
                            ),
                            array(
                                'param_name' => 'tdc_css',
                                'value' => '',
                                'type' => 'tdc_css_editor',
                                'heading' => '',
                                'group' => 'Design options',
                            )

                        )
                    )
                )
            );

            td_api_block::add('td_block_contractors_notifications',
                array(
                    "map_in_visual_composer" => true,
                    "map_in_td_composer" => true,
                    "name" => 'Contractors Notifications',
                    "base" => 'td_block_contractors_notifications',
                    "class" => 'td_block_contractors_notifications',
                    "controls" => "full",
                    "category" => 'Blocks',
                    "tdc_category" => 'External',
                    //'icon' => 'icon-pagebuilder-td_block_77',
                    'file' => $this->plugin_path . '/blocks/td_block_contractors_notifications.php',
                    'params' => array_merge(
                        array(

                            array(
                                'param_name' => 'el_class',
                                'type' => 'textfield',
                                'value' => '',
                                'heading' => 'Extra class',
                                'description' => 'Style particular content element differently - add a class name and refer to it in custom CSS',
                                'class' => 'tdc-textfield-extrabig',
                            ),
                            array(
                                'param_name' => 'tdc_css',
                                'value' => '',
                                'type' => 'tdc_css_editor',
                                'heading' => '',
                                'group' => 'Design options',
                            )

                        )
                    )
                )
            );

            td_api_block::add( 'tds_my_account_yr',
                array(
                    "map_in_td_composer" => true,
                    "name" => 'Page account (YR)',
                    "base" => 'tds_my_account_yr',
                    'tdc_category' => 'Blocks',
                    'tdc_style_params' => array(
                        'show_version',
                        'show_notif',
                        'enable_pag',
                        'per_page',
                        'el_class',
                    ),
                    "file" => $this->plugin_path . '/blocks/tds_my_account_yr.php',
                    "params" => array_merge(
                        array(
                            array(
                                "param_name" => "show_version",
                                "type" => "dropdown",
                                "value" => array(
                                    'Dashboard' => '',
                                    'Account settings' => 'settings',
                                    'Subscriptions' => 'subscriptions',
                                ),
                                "heading" => 'Show in composer',
                                "description" => "",
                                "holder" => "div",
                                "class" => "tdc-dropdown-big",
                                "group" => "",
                            ),

                            array(
                                "param_name" => "separator",
                                "type" => "text_separator",
                                'heading' => 'General',
                                "value" => "",
                                "class" => "",
                                "group" => '',
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "",
                                "heading" => 'Accent color',
                                "param_name" => "accent_color",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "",
                                "heading" => 'Links hover color',
                                "param_name" => "a_color_h",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),
                            array(
                                "param_name" => "separator",
                                "type" => "horizontal_separator",
                                "value" => "",
                                "class" => "tdc-separator-small",
                                "group" => "",
                            ),
                        ),
                        td_config_helper::get_map_block_font_array( 'f_text', true, 'General text', '', '', 'tdc-s-global-font' ),

                        array(
                            array(
                                "param_name" => "separator",
                                "type" => "text_separator",
                                'heading' => 'Sections',
                                "value" => "",
                                "class" => "",
                                "group" => '',
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "",
                                "heading" => 'Title color',
                                "param_name" => "sec_color",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "",
                                "heading" => 'Description color',
                                "param_name" => "sec_descr_color",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "",
                                "heading" => 'Separators color',
                                "param_name" => "sec_sep_color",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),
                            array(
                                "param_name" => "separator",
                                "type" => "text_separator",
                                'heading' => 'Sidebar',
                                "value" => "",
                                "class" => "",
                                "group" => '',
                            ),
                            array(
                                "param_name" => "side_width",
                                "type" => "textfield-responsive",
                                "value" => '',
                                "heading" => "Width",
                                "description" => "",
                                "holder" => "div",
                                "class" => "tdc-textfield-big",
                                "placeholder" => "200"
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "",
                                "heading" => 'Right separator color',
                                "param_name" => "sep_color",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),
                            array(
                                "param_name" => "separator",
                                "type" => "text_separator",
                                'heading' => 'Navigation links',
                                "value" => "",
                                "class" => "tdc-separator-small",
                                "group" => '',
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "",
                                "heading" => 'Text color',
                                "param_name" => "nav_color",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "",
                                "heading" => 'Icons color',
                                "param_name" => "nav_ico_color",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "tdc-colorpicker-double-a",
                                "heading" => 'Background color',
                                "param_name" => "nav_ico_bg",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "tdc-colorpicker-double-b",
                                "heading" => 'Hover/active background color',
                                "param_name" => "nav_ico_bg_h",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),

                            array(
                                "param_name" => "separator",
                                "type" => "text_separator",
                                'heading' => 'Forms',
                                "value" => "",
                                "class" => "",
                                "group" => '',
                            ),
                            array(
                                "param_name" => "separator",
                                "type" => "text_separator",
                                'heading' => 'Labels',
                                "value" => "",
                                "class" => "tdc-separator-small",
                                "group" => '',
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "",
                                "heading" => 'Text color',
                                "param_name" => "label_color",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),
                            array(
                                "param_name" => "separator",
                                "type" => "horizontal_separator",
                                "value" => "",
                                "class" => "tdc-separator-small",
                                "group" => "",
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "",
                                "heading" => 'Tooltips text color',
                                "param_name" => "tip_color",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "",
                                "heading" => 'Tooltips background color',
                                "param_name" => "tip_bg",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),
                            array(
                                "param_name" => "tip_radius",
                                "type" => "textfield-responsive",
                                "value" => '',
                                "heading" => "Tooltips border radius",
                                "description" => "",
                                "holder" => "div",
                                "class" => "tdc-textfield-big",
                                "placeholder" => "2"
                            ),
                            array(
                                "param_name" => "separator",
                                "type" => "text_separator",
                                'heading' => 'Inputs',
                                "value" => "",
                                "class" => "tdc-separator-small",
                                "group" => '',
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "",
                                "heading" => 'Text color',
                                "param_name" => "input_color",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "",
                                "heading" => 'Background color',
                                "param_name" => "input_bg",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),
                            array(
                                "param_name" => "separator",
                                "type" => "horizontal_separator",
                                "value" => "",
                                "class" => "tdc-separator-small",
                                "group" => "",
                            ),
                            array(
                                "param_name" => "all_input_border",
                                "type" => "textfield-responsive",
                                "value" => '',
                                "heading" => "Border size",
                                "description" => "",
                                "holder" => "div",
                                "class" => "tdc-textfield-big",
                                "placeholder" => "2"
                            ),
                            array(
                                "param_name" => "all_input_border_style",
                                "type" => "dropdown-responsive",
                                "value" => array(
                                    'Solid' => 'solid',
                                    'Dashed' => 'dashed',
                                    'Dotted' => 'dotted',
                                    'Double' => 'double',
                                ),
                                "heading" => 'Border style',
                                "description" => "",
                                "holder" => "div",
                                "class" => "tdc-dropdown-big",
                                "group" => "",
                            ),
                            array(
                                "param_name" => "input_radius",
                                "type" => "textfield-responsive",
                                "value" => '',
                                "heading" => "Border radius",
                                "description" => "",
                                "holder" => "div",
                                "class" => "tdc-textfield-big",
                                "placeholder" => "5"
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "",
                                "heading" => 'Border color',
                                "param_name" => "all_input_border_color",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),

                            array(
                                "param_name" => "separator",
                                "type" => "text_separator",
                                'heading' => 'Tables',
                                "value" => "",
                                "class" => "",
                                "group" => '',
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "",
                                "heading" => 'Borders color',
                                "param_name" => "tabl_border_color",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),
                            array(
                                "param_name" => "separator",
                                "type" => "horizontal_separator",
                                "value" => "",
                                "class" => "tdc-separator-small",
                                "group" => "",
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "",
                                "heading" => 'Head text color',
                                "param_name" => "tabl_head_color",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),
                            array(
                                "param_name" => "separator",
                                "type" => "horizontal_separator",
                                "value" => "",
                                "class" => "tdc-separator-small",
                                "group" => "",
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "",
                                "heading" => 'Body text color',
                                "param_name" => "tabl_body_color",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "",
                                "heading" => "Hover/expanded row background",
                                "param_name" => "tabl_hover_bg",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "",
                                "heading" => "Expanded row info background",
                                "param_name" => "tabl_info_bg",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),
                            array(
                                "param_name" => "separator",
                                "type" => "horizontal_separator",
                                "value" => "",
                                "class" => "tdc-separator-small",
                                "group" => "",
                            ),
                            array(
                                "param_name" => "enable_pag",
                                "type" => "checkbox",
                                "value" => 'yes',
                                "heading" => "Enable pagination",
                                "description" => "",
                                "holder" => "div",
                                "class" => "",
                            ),
                            array(
                                "param_name" => "per_page",
                                "type" => "textfield",
                                "value" => '',
                                "heading" => "Per page",
                                "description" => "",
                                "holder" => "div",
                                "class" => "tdc-textfield-small",
                                "placeholder" => "10"
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "tdc-colorpicker-double-a",
                                "heading" => "Pagination background color",
                                "param_name" => "pag_bg",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "tdc-colorpicker-double-b",
                                "heading" => "Pagination background hover color",
                                "param_name" => "pag_bg_h",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "tdc-colorpicker-triple-a",
                                "heading" => "Pagination text color",
                                "param_name" => "pag_color",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "tdc-colorpicker-triple-b",
                                "heading" => "Pagination text hover color",
                                "param_name" => "pag_color_h",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "tdc-colorpicker-triple-c",
                                "heading" => "Pagination text active color",
                                "param_name" => "pag_color_a",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),

                            array(
                                "param_name" => "separator",
                                "type" => "text_separator",
                                'heading' => 'Lists',
                                "value" => "",
                                "class" => "",
                                "group" => '',
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "",
                                "heading" => 'Labels text color',
                                "param_name" => "list_label_color",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "",
                                "heading" => 'Values text color',
                                "param_name" => "list_val_color",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),

                            array(
                                "param_name" => "separator",
                                "type" => "text_separator",
                                'heading' => 'Buttons',
                                "value" => "",
                                "class" => "",
                                "group" => '',
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "tdc-colorpicker-double-a",
                                "heading" => 'Text color',
                                "param_name" => "btn_color",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "tdc-colorpicker-double-b",
                                "heading" => 'Text hover color',
                                "param_name" => "btn_color_h",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "",
                                "heading" => 'Background hover color',
                                "param_name" => "btn_bg_h",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),
                            array(
                                "param_name" => "separator",
                                "type" => "horizontal_separator",
                                "value" => "",
                                "class" => "tdc-separator-small",
                                "group" => "",
                            ),
                            array(
                                "param_name" => "btn_radius",
                                "type" => "textfield-responsive",
                                "value" => '',
                                "heading" => "Border radius",
                                "description" => "",
                                "holder" => "div",
                                "class" => "tdc-textfield-big",
                                "placeholder" => "5"
                            ),

                            array(
                                "param_name" => "separator",
                                "type" => "text_separator",
                                'heading' => 'Publishing rights counters',
                                "value" => "",
                                "class" => "",
                                "group" => '',
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "",
                                "heading" => 'Background color',
                                "param_name" => "pr_bg",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "",
                                "heading" => 'Post type text color',
                                "param_name" => "pr_type_color",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),
                            array(
                                "param_name" => "separator",
                                "type" => "horizontal_separator",
                                "value" => "",
                                "class" => "tdc-separator-small",
                                "group" => "",
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "",
                                "heading" => 'Counter background color',
                                "param_name" => "pr_count_bg",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "",
                                "heading" => 'Counter text color',
                                "param_name" => "pr_count_color",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),
                            array(
                                "param_name" => "separator",
                                "type" => "horizontal_separator",
                                "value" => "",
                                "class" => "tdc-separator-small",
                                "group" => "",
                            ),
                            array(
                                "param_name" => "pr_radius",
                                "type" => "textfield-responsive",
                                "value" => '',
                                "heading" => "Border radius",
                                "description" => "",
                                "holder" => "div",
                                "class" => "tdc-textfield-big",
                                "placeholder" => "5"
                            ),


                            array(
                                "param_name" => "separator",
                                "type" => "text_separator",
                                'heading' => 'Notification messages',
                                "value" => "",
                                "class" => "",
                                "group" => '',
                            ),
                            array(
                                "param_name" => "show_notif",
                                "type" => "checkbox",
                                "value" => '',
                                "heading" => "Show in composer",
                                "description" => "",
                                "holder" => "div",
                                "class" => "",
                            ),
                            array(
                                "param_name" => "notif_radius",
                                "type" => "textfield-responsive",
                                "value" => '',
                                "heading" => "Border radius",
                                "description" => "",
                                "holder" => "div",
                                "class" => "tdc-textfield-big",
                                "placeholder" => "3"
                            ),
                            array(
                                "param_name" => "separator",
                                "type" => "horizontal_separator",
                                "value" => "",
                                "class" => "tdc-separator-small",
                                "group" => "",
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "",
                                "heading" => 'Information accent color',
                                "param_name" => "notif_info_color",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "",
                                "heading" => 'Success accent color',
                                "param_name" => "notif_succ_color",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),
                            array(
                                "type" => "colorpicker",
                                "holder" => "div",
                                "class" => "",
                                "heading" => 'Error accent color',
                                "param_name" => "notif_error_color",
                                "value" => '',
                                "description" => '',
                                "group" => "",
                            ),

                            array(
                                "param_name" => "separator",
                                "type"       => "text_separator",
                                'heading'    => 'Pages',
                                "value"      => "",
                                "class"      => "tdc-separator",
                                "group"      => "Custom pages"
                            ),
                            array(
                                "param_name" => "pages_header",
                                "type" => "pages_header",
                                "value" => "",
                                "class" => '',
                                "group" => 'Custom pages',
                                "id_heading_txt" => 'ID',
                            ),
                            array(
                                "param_name" => "page_0_id",
                                "type" => "textfield",
                                "value" => '',
                                "heading" => 'Dashboard page ID',
                                "description" => "",
                                "placeholder" => "Def",
                                "holder" => "div",
                                "class" => "tdc-textfield-extrabig tdc-page-controller tdc-page-id",
                                'group'      => 'Custom pages',
                            ),
                            array(
                                "param_name" => "page_0_title",
                                "type" => "textfield",
                                "value" => '',
                                "heading" => 'Dashboard page title',
                                "description" => "",
                                "placeholder" => "Dashboard",
                                "holder" => "div",
                                "class" => "tdc-textfield-extrabig tdc-page-controller tdc-page-title",
                                'group'      => 'Custom pages',
                            ),
                            array(
                                'param_name' => 'page_0_tdicon',
                                'type' => 'icon',
                                'heading' => 'Dashboard page icon',
                                'class' => 'tdc-textfield-small tdc-page-controller tdc-page-icon',
                                'value' => '',
                                "group"       => 'Custom pages'
                            ),
                            array(
                                "param_name" => "page_6_id",
                                "type" => "textfield",
                                "value" => '',
                                "heading" => 'Account settings page ID',
                                "description" => "",
                                "placeholder" => "Def",
                                "holder" => "div",
                                "class" => "tdc-textfield-extrabig tdc-page-controller tdc-page-id",
                                'group'      => 'Custom pages',
                            ),
                            array(
                                "param_name" => "page_6_title",
                                "type" => "textfield",
                                "value" => '',
                                "heading" => 'Dashboard page title',
                                "description" => "",
                                "placeholder" => "Account settings",
                                "holder" => "div",
                                "class" => "tdc-textfield-extrabig tdc-page-controller tdc-page-title",
                                'group'      => 'Custom pages',
                            ),
                            array(
                                'param_name' => 'page_6_tdicon',
                                'type' => 'icon',
                                'heading' => 'Account settings page icon',
                                'class' => 'tdc-textfield-small tdc-page-controller tdc-page-icon',
                                'value' => '',
                                "group"       => 'Custom pages'
                            ),
                            array(
                                "param_name" => "page_1_id",
                                "type" => "textfield",
                                "value" => '',
                                "heading" => 'Page 1 ID',
                                "description" => "",
                                "placeholder" => "-",
                                "holder" => "div",
                                "class" => "tdc-textfield-extrabig tdc-page-controller tdc-page-id",
                                'group'      => 'Custom pages',
                            ),
                            array(
                                "param_name" => "page_1_title",
                                "type" => "textfield",
                                "value" => '',
                                "heading" => 'Page 1 title',
                                "description" => "",
                                "placeholder" => "Page 1 title",
                                "holder" => "div",
                                "class" => "tdc-textfield-extrabig tdc-page-controller tdc-page-title",
                                'group'      => 'Custom pages',
                            ),
                            array(
                                'param_name' => 'page_1_tdicon',
                                'type' => 'icon',
                                'heading' => 'Page 1 icon',
                                'class' => 'tdc-textfield-small tdc-page-controller tdc-page-icon',
                                'value' => '',
                                "group"       => 'Custom pages'
                            ),
                            array(
                                "param_name" => "page_2_id",
                                "type" => "textfield",
                                "value" => '',
                                "heading" => 'Page 2 ID',
                                "description" => "",
                                "placeholder" => "-",
                                "holder" => "div",
                                "class" => "tdc-textfield-extrabig tdc-page-controller tdc-page-id",
                                'group'      => 'Custom pages',
                            ),
                            array(
                                "param_name" => "page_2_title",
                                "type" => "textfield",
                                "value" => '',
                                "heading" => 'Page 2 title',
                                "description" => "",
                                "placeholder" => "Page 2 title",
                                "holder" => "div",
                                "class" => "tdc-textfield-extrabig tdc-page-controller tdc-page-title",
                                'group'      => 'Custom pages',
                            ),
                            array(
                                'param_name' => 'page_2_tdicon',
                                'type' => 'icon',
                                'heading' => 'Page 2 icon',
                                'class' => 'tdc-textfield-small tdc-page-controller tdc-page-icon',
                                'value' => '',
                                "group"       => 'Custom pages'
                            ),
                            array(
                                "param_name" => "page_3_id",
                                "type" => "textfield",
                                "value" => '',
                                "heading" => 'Page 3 ID',
                                "description" => "",
                                "placeholder" => "-",
                                "holder" => "div",
                                "class" => "tdc-textfield-extrabig tdc-page-controller tdc-page-id",
                                'group'      => 'Custom pages',
                            ),
                            array(
                                "param_name" => "page_3_title",
                                "type" => "textfield",
                                "value" => '',
                                "heading" => 'Page 3 title',
                                "description" => "",
                                "placeholder" => "Page 3 title",
                                "holder" => "div",
                                "class" => "tdc-textfield-extrabig tdc-page-controller tdc-page-title",
                                'group'      => 'Custom pages',
                            ),
                            array(
                                'param_name' => 'page_3_tdicon',
                                'type' => 'icon',
                                'heading' => 'Page 3 icon',
                                'class' => 'tdc-textfield-small tdc-page-controller tdc-page-icon',
                                'value' => '',
                                "group"       => 'Custom pages'
                            ),
                            array(
                                "param_name" => "page_4_id",
                                "type" => "textfield",
                                "value" => '',
                                "heading" => 'Page 4 ID',
                                "description" => "",
                                "placeholder" => "-",
                                "holder" => "div",
                                "class" => "tdc-textfield-extrabig tdc-page-controller tdc-page-id",
                                'group'      => 'Custom pages',
                            ),
                            array(
                                "param_name" => "page_4_title",
                                "type" => "textfield",
                                "value" => '',
                                "heading" => 'Page 4 title',
                                "description" => "",
                                "placeholder" => "Page 5 title",
                                "holder" => "div",
                                "class" => "tdc-textfield-extrabig tdc-page-controller tdc-page-title",
                                'group'      => 'Custom pages',
                            ),
                            array(
                                'param_name' => 'page_4_tdicon',
                                'type' => 'icon',
                                'heading' => 'Page 4 icon',
                                'class' => 'tdc-textfield-small tdc-page-controller tdc-page-icon',
                                'value' => '',
                                "group"       => 'Custom pages'
                            ),
                            array(
                                "param_name" => "page_5_id",
                                "type" => "textfield",
                                "value" => '',
                                "heading" => 'Page 5 ID',
                                "description" => "",
                                "placeholder" => "-",
                                "holder" => "div",
                                "class" => "tdc-textfield-extrabig tdc-page-controller tdc-page-id",
                                'group'      => 'Custom pages',
                            ),
                            array(
                                "param_name" => "page_5_title",
                                "type" => "textfield",
                                "value" => '',
                                "heading" => 'Page 5 title',
                                "description" => "",
                                "placeholder" => "Page 5 title",
                                "holder" => "div",
                                "class" => "tdc-textfield-extrabig tdc-page-controller tdc-page-title",
                                'group'      => 'Custom pages',
                            ),
                            array(
                                'param_name' => 'page_5_tdicon',
                                'type' => 'icon',
                                'heading' => 'Page 5 icon',
                                'class' => 'tdc-textfield-small tdc-page-controller tdc-page-icon',
                                'value' => '',
                                "group"       => 'Custom pages'
                            ),
                        ),
                        self::get_block_style()
                    )
                )
            );

            td_api_block::add('td_block_contractors_categories',
                array(
                    "map_in_visual_composer" => true,
                    "map_in_td_composer" => true,
                    "name" => 'Contractors Categories',
                    "base" => 'td_block_contractors_categories',
                    "class" => 'td_block_contractors_categories',
                    "controls" => "full",
                    "category" => 'Blocks',
                    "tdc_category" => 'External',
                    //'icon' => 'icon-pagebuilder-td_block_77',
                    'file' => $this->plugin_path . '/blocks/td_block_contractors_categories.php',
                    'params' => array_merge(
                        array(
                            array(
                                "param_name" => "separator",
                                "type"       => "text_separator",
                                'heading'    => 'General settings',
                                "value"      => "",
                                "class"      => "tdc-separator-small",
                                "group"       => '',
                            ),
                            array(
                                "param_name" => "contractors_taxonomy",
                                "type" => "textfield-responsive",
                                "value" => '',
                                "heading" => "Taxonomy",
                                "description" => "Insert the taxonomy",
                                "holder" => "div",
                                "class" => "tdc-textfield-big",
                                "placeholder" => "ex.: Category"
                            ),
                            array(
                                "param_name" => "contractors_user_role",
                                "type" => "textfield-responsive",
                                "value" => '',
                                "heading" => "User Role",
                                "description" => "Insert the user role",
                                "holder" => "div",
                                "class" => "tdc-textfield-big",
                                "placeholder" => "ex.: Admin"
                            ),
                            array(
                                "param_name" => "separator",
                                "type"       => "text_separator",
                                'heading'    => 'Plan settings',
                                "value"      => "",
                                "class"      => "tdc-separator-small",
                                "group"       => '',
                            ),
                            array(
                                "param_name" => "contractors_plan_id1",
                                "type" => "textfield-responsive",
                                "value" => '',
                                "heading" => "Plan ID",
                                "description" => "Insert the contractor plan ID1",
                                "holder" => "div",
                                "class" => "tdc-textfield-small",
                                "placeholder" => "Ex.: 1"
                            ),
                            array(
                                "param_name" => "contractors_plan_id1_categories_limit",
                                "type" => "textfield-responsive",
                                "value" => '',
                                "heading" => "Plan ID Categories Limit",
                                "description" => "Insert the contractor plan ID1 categories limit",
                                "holder" => "div",
                                "class" => "tdc-textfield-small",
                                "placeholder" => "Ex.: 5"
                            ),
                            array(
                                "param_name" => "separator",
                                "type" => "horizontal_separator",
                                "value" => "",
                                "class" => "tdc-separator-small",
                                "group" => "",
                            ),
                            array(
                                "param_name" => "contractors_plan_id2",
                                "type" => "textfield-responsive",
                                "value" => '',
                                "heading" => "Plan ID",
                                "description" => "Insert the contractor plan ID2",
                                "holder" => "div",
                                "class" => "tdc-textfield-small",
                                "placeholder" => "Ex.: 2"
                            ),
                            array(
                                "param_name" => "contractors_plan_id2_categories_limit",
                                "type" => "textfield-responsive",
                                "value" => '',
                                "heading" => "Plan ID Categories Limit",
                                "description" => "Insert the contractor plan ID2 categories limit",
                                "holder" => "div",
                                "class" => "tdc-textfield-small",
                                "placeholder" => "Ex.: 3"
                            ),
                            array(
                                "param_name" => "separator",
                                "type" => "horizontal_separator",
                                "value" => "",
                                "class" => "tdc-separator-small",
                                "group" => "",
                            ),
                            array(
                                "param_name" => "contractors_plan_id3",
                                "type" => "textfield-responsive",
                                "value" => '',
                                "heading" => "Plan ID",
                                "description" => "Insert the contractor plan ID3",
                                "holder" => "div",
                                "class" => "tdc-textfield-small",
                                "placeholder" => "Ex.: 3"
                            ),
                            array(
                                "param_name" => "contractors_plan_id3_categories_limit",
                                "type" => "textfield-responsive",
                                "value" => '',
                                "heading" => "Plan ID Categories Limit",
                                "description" => "Insert the contractor plan ID3 categories limit",
                                "holder" => "div",
                                "class" => "tdc-textfield-small",
                                "placeholder" => "Ex.: 1"
                            ),
                            array(
                                'param_name' => 'el_class',
                                'type' => 'textfield',
                                'value' => '',
                                'heading' => 'Extra class',
                                'description' => 'Style particular content element differently - add a class name and refer to it in custom CSS',
                                'class' => 'tdc-textfield-extrabig',
                            ),
                            array(
                                'param_name' => 'tdc_css',
                                'value' => '',
                                'type' => 'tdc_css_editor',
                                'heading' => '',
                                'group' => 'Design options',
                            )

                        )
                    )
                )
            );
        });


    }


    static function get_block_style() {
        return array(
            array(
                "param_name" => "separator",
                "type" => "horizontal_separator",
                "value" => "",
                "class" => ""
            ),
            array(
                'param_name' => 'el_class',
                'type' => 'textfield',
                'value' => '',
                'heading' => 'Extra class',
                'description' => 'Style particular content element differently - add a class name and refer to it in custom CSS',
                'class' => 'tdc-textfield-extrabig',
            ),
            array(
                'param_name' => 'tdc_css',
                'value' => '',
                'type' => 'tdc_css_editor',
                'heading' => '',
                'group' => 'Design options',
            )
        );
    }


}